name: CI/CD DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      
      - name: Install Project Dependencies
        run: |
          npm cache clean --force
          npm install 
          npm install bcrypt@latest 
          npm install bcryptjs@latest 
          npm install snyk -g
          npm install snyk-to-html -g
          pip install junit2html

      - name: Gitleaks Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--path=. --report-format=json --report-path=gitleaks-report.json"
        continue-on-error: true

      - name: Scanning Project Dependencies - SCA
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --all-projects --json-file-output=results-opensource.json || true
          snyk-to-html -i results-opensource.json -o results-opensource.html

      - name: Scanning Source Code - SAST
        run: |
          snyk code test --json-file-output=results-code.json || true
          snyk-to-html -i results-code.json -o results-code.html

      - name: Docker Container Scanning
        run: |
          docker build . -t myapp
          snyk container test --file=Dockerfile --json-file-output=results-container.json myapp || true
          snyk-to-html -i results-container.json -o results-container.html

      - name: Scanning Terraform Scripts - IaC
        run: |
          snyk iac test --json-file-output=results-iac.json || true
          snyk-to-html -i results-iac.json -o results-iac.html

      - name: Running DAST Scan 
        id: Scan
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@v1.0.0
        with:
          target-url: 'https://juice-shop.herokuapp.com/'
          output-filename: 'dastardly-report.xml'

      - name: Processing DAST Report
        run: |
          cd ${GITHUB_WORKSPACE}
          junit2html dastardly-report.xml dastardly-report.html

      - name: Uploading Reports to Artifacts
        uses: actions/upload-artifact@v3.1.2 
        with:
          name: All-Reports
          path: |
            dastardly-report.html
            gitleaks-report.json
            results-opensource.html
            results-code.html
            results-container.html
            results-iac.html
