name: CI/CD DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify repository contents
        run: ls -l

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12' # Change this to a compatible Node.js version

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
          npm install bcrypt@latest || npm install bcryptjs@latest

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Run Snyk for Docker scan
        continue-on-error: true
        uses: snyk/actions/docker@v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: myapp

      - name: Run Snyk for Code scan
        continue-on-error: true
        uses: snyk/actions/code@v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@v0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: ./terraform/ # Adjust this path to your IaC file

      - name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Notify Snyk Docker scan results
        run: |
          echo "Snyk Docker scan completed. Review the results in the Snyk dashboard."

      - name: Notify Snyk Code scan results
        run: |
          echo "Snyk Code scan completed. Review the results in the Snyk dashboard."

      - name: Notify Snyk IaC scan results
        run: |
          echo "Snyk IaC scan completed. Review the results in the Snyk dashboard."
