name: CI/CD DevSecOps Pipeline
name: Snyk SCA, Code, IaC and Container CLI monitor example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
          npm install && npm install bcrypt@latest || npm install bcryptjs@latest

      - name: Setup Snyk + snyk-to-html
        run: |
          npm install snyk -g
          npm install snyk-to-html -g
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Open Source Scanning
        run: snyk test --all-projects --json-file-output=results-opensource.json
      - name: Convert Snyk Open Source results to HTML
        run: snyk-to-html -i results-opensource.json -o results-opensource.html
      - name: Upload Snyk Open Source results
        uses: actions/upload-artifact@v2
        with:
          name: snyk-opensource-report
          path: results-opensource.html

      - name: Snyk Code Scanning
        run: snyk code test --json-file-output=results-code.json || true
      - name: Convert Snyk Code results to HTML
        run: snyk-to-html -i results-code.json -o results-code.html
      - name: Upload Snyk Code results
        uses: actions/upload-artifact@v2
        with:
          name: snyk-code-report
          path: results-code.html

      - name: Snyk Container Scanning
        run: |
          docker build . -t myapp
          snyk container test --file=Dockerfile --json-file-output=results-container.json myapp || true
      - name: Convert Snyk Container results to HTML
        run: snyk-to-html -i results-container.json -o results-container.html
      - name: Upload Snyk Container results
        uses: actions/upload-artifact@v2
        with:
          name: snyk-container-report
          path: results-container.html

      - name: Snyk IaC Scanning
        run: snyk iac test --json-file-output=results-iac.json || true
      - name: Convert Snyk IaC results to HTML
        run: snyk-to-html -i results-iac.json -o results-iac.html
      - name: Upload Snyk IaC results
        uses: actions/upload-artifact@v2
        with:
          name: snyk-iac-report
          path: results-iac.html
