name: CI/CD DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Terrascan
        run: |
          curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
          tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
          sudo install terrascan /usr/local/bin && rm terrascan

      - name: Verify Terrascan installation
        run: terrascan version

      - name: List Terraform files
        run: ls -l ./terraform # Adjust this path to the directory containing your Terraform files

      - name: Terrascan Scan
        working-directory: ./terraform # Adjust this path to the directory containing your Terraform files
        run: terrascan scan -o sarif > terrascan-results.sarif

      - name: Notify CodeQL results
        run: |
          echo "CodeQL analysis completed. Review the results at [CodeQL results URL]"

      - name: Notify Docker scan results
        run: |
          echo "Docker security scan completed. Review the results at [Docker scan results URL]"

      - name: Notify TFSec results
        run: |
          echo "TFSec scan completed. Review the results at [TFSec results URL]"
