name: CI/CD DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Dependabot security update
        uses: dependabot/dependabot-core@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: CodeQL analysis
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript

      - name: Docker security scan
        run: docker scan myapp

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Install TFSec
        run: |
          wget -qO- https://github.com/aquasecurity/tfsec/releases/download/v0.58.7/tfsec-linux-amd64 > tfsec && \
          chmod +x tfsec && \
          sudo mv tfsec /usr/local/bin/

      - name: TFSec Scan
        run: tfsec .

      - name: Upload CodeQL scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeql-results.sarif

      - name: Run Terraform Security Scan
        run: tfsec .

      - name: Save combined report
        run: |
          # Combine SARIF files into a single report
          cat codeql-results.sarif > combined_report.sarif
          cat tfsec-results.sarif >> combined_report.sarif

      - name: Upload combined report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: combined-report
          path: combined_report.sarif

      - name: Send combined report via GitHub notification
        if: always()
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const contents = fs.readFileSync('combined_report.sarif', 'utf8');
            github.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'combined_report.sarif',
              message: 'Upload combined security scan report',
              content: Buffer.from(contents).toString('base64'),
              committer: {
                name: 'GitHub Actions',
                email: 'actions@github.com'
              },
              author: {
                name: 'GitHub Actions',
                email: 'actions@github.com'
              }
            });
