name: CI/CD DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      
      - name: Install Project Dependencies
        run: |
          npm cache clean --force
          npm install 
          npm install bcrypt@latest 
          npm install bcryptjs@latest 
          npm install snyk -g
          npm install snyk-to-html -g

      - name: Gitleaks Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--path=. --report-format=json --report-path=gitleaks-report.json"
        continue-on-error: true

      - name: Scanning Project Dependencies - SCA
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --all-projects --json-file-output=results-opensource.json
        continue-on-error: true

      - name: Scanning Source Code - SAST
        run: |
          snyk code test --json-file-output=results-code.json
        continue-on-error: true

      - name: Docker Container Scanning
        run: |
          docker build . -t myapp
          snyk container test --file=Dockerfile --json-file-output=results-container.json myapp
        continue-on-error: true

      - name: Scanning Terraform Scripts - IaC
        run: |
          snyk iac test --json-file-output=results-iac.json
        continue-on-error: true

      - name: Run Application
        run: |
          docker run --name dvna -p 9090:9090 -d appsecco/dvna:sqlite && sleep 5

      - name: Running DAST Scan 
        id: Scan
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@v1.0.0
        with:
          target-url: 'http://localhost:9090/'
          output-filename: 'dastardly-report.xml'

      - name: Uploading Reports to Artifacts
        uses: actions/upload-artifact@v3.1.2 
        with:
          name: All-Reports
          path: |
            dastardly-report.xml
            gitleaks-report.json
            results-opensource.json
            results-code.json
            results-container.json
            results-iac.json

      - name: Import Snyk SCA Report to DefectDojo
        uses: portswigger-cloud/defectdojo-import-scan@v1.0.1
        with:
          defectdojo_base_url: 'https://demo.defectdojo.org/'
          defectdojo_api_key: ${{ secrets.DEFECTDOJO_API_KEY }}    
          engagement_id: '14'                                      
          file_path: 'results-opensource.json'                     
          scan_type: 'Snyk SCA'                                   
          scan_date: '2024-07-08'                                 
          environment: 'Development'                              
          verified: 'true'                                         

      - name: Import Snyk SAST Report to DefectDojo
        uses: portswigger-cloud/defectdojo-import-scan@v1.0.1
        with:
          defectdojo_base_url: 'https://demo.defectdojo.org/'
          defectdojo_api_key: ${{ secrets.DEFECTDOJO_API_KEY }}
          engagement_id: '14'
          file_path: 'results-code.json'
          scan_type: 'Snyk SAST'
          scan_date: '2024-07-08'
          environment: 'Development'
          verified: 'true'

      - name: Import Snyk Container Scan Report to DefectDojo
        uses: portswigger-cloud/defectdojo-import-scan@v1.0.1
        with:
          defectdojo_base_url: 'https://demo.defectdojo.org/'
          defectdojo_api_key: ${{ secrets.DEFECTDOJO_API_KEY }}
          engagement_id: '14'
          file_path: 'results-container.json'
          scan_type: 'Snyk Container Scan'
          scan_date: '2024-07-08'
          environment: 'Development'
          verified: 'true'

      - name: Import Snyk IaC Report to DefectDojo
        uses: portswigger-cloud/defectdojo-import-scan@v1.0.1
        with:
          defectdojo_base_url: 'https://demo.defectdojo.org/'
          defectdojo_api_key: ${{ secrets.DEFECTDOJO_API_KEY }}
          engagement_id: '14'
          file_path: 'results-iac.json'
          scan_type: 'Snyk IaC'
          scan_date: '2024-07-08'
          environment: 'Development'
          verified: 'true'

      - name: Import DAST Scan Report to DefectDojo
        uses: portswigger-cloud/defectdojo-import-scan@v1.0.1
        with:
          defectdojo_base_url: 'https://demo.defectdojo.org/'
          defectdojo_api_key: ${{ secrets.DEFECTDOJO_API_KEY }}
          engagement_id: '14'
          file_path: 'dastardly-report.xml'
          scan_type: 'DAST Scan'
          scan_date: '2024-07-08'
          environment: 'Development'
          verified: 'true'
