name: CI/CD DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify repository contents
        run: ls -l

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12' # Change this to a compatible Node.js version

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
          npm install bcrypt@latest || npm install bcryptjs@latest

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Set up Snyk
        uses: snyk/actions/setup@v2.2.0
        with:
          version: 'latest'

      - name: Snyk Docker scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk container test myapp --file=Dockerfile

      - name: Snyk Code scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test

      - name: Snyk IaC scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk iac test --severity-threshold=high

      - name: Notify Snyk Docker scan results
        run: |
          echo "Snyk Docker scan completed. Review the results in the Snyk dashboard."

      - name: Notify Snyk Code scan results
        run: |
          echo "Snyk Code scan completed. Review the results in the Snyk dashboard."

      - name: Notify Snyk IaC scan results
        run: |
          echo "Snyk IaC scan completed. Review the results in the Snyk dashboard."
